### ISSUE TITLE
Different evaluation results

### ISSUE THREAD

**Issue by kamse** [caozidong/Depth-Completion#2]
Evaluation results on [val]:
[Loss]: 0.00000000
[MAE_Paint]: 0.70549407
[RMSE_Paint]: 3.48612628
[SSIM_Metric]: 0.66966505
[Delta1]: 0.51564395
[Delta2]: 0.54521561
[Delta3]: 0.60502511
[Delta4]: 0.71139991
[Delta5]: 0.80766916
[RMSE]: 1.86711710

I ran run_eval.py on the Matterport3D dataset and got quite different results.
Visualizing the depth, the quality seems inferior than your paper. Do you know why?
![0000000001](https://user-images.githubusercontent.com/34829989/139169507-6c42c8aa-c313-489a-8fb3-3a3569c5eb03.png)

**Comment by caozidong** [comment]
Hi, in my matterportdataset L159-161, you need to use NEAREST style to interpolation. The difference may occur because of different environments.

**Comment by kamse** [comment]
Oh, I see !!
Running it again with the nearest Interpolation works fine.
Thank you so much for quick reply.

[Loss]: 0.00000000
[MAE_Paint]: 0.38938830
[RMSE_Paint]: 1.42475963
[SSIM_Metric]: 0.74327183
[Delta1]: 0.67106819
[Delta2]: 0.72549075
[Delta3]: 0.79456913
[Delta4]: 0.86339188
[Delta5]: 0.90506095
[RMSE]: 1.19363296
